// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fcatCpp
std::vector<std::string> fcatCpp(const std::vector<std::string>& fasta);
RcppExport SEXP _protViz_fcatCpp(SEXP fastaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type fasta(fastaSEXP);
    rcpp_result_gen = Rcpp::wrap(fcatCpp(fasta));
    return rcpp_result_gen;
END_RCPP
}
// trypticDigestCpp
std::vector<std::string> trypticDigestCpp(const std::vector<std::string>& fasta);
RcppExport SEXP _protViz_trypticDigestCpp(SEXP fastaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type fasta(fastaSEXP);
    rcpp_result_gen = Rcpp::wrap(trypticDigestCpp(fasta));
    return rcpp_result_gen;
END_RCPP
}
