// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fcat_FASTA
StringVector fcat_FASTA(const StringVector& fasta);
RcppExport SEXP _protViz_fcat_FASTA(SEXP fastaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type fasta(fastaSEXP);
    rcpp_result_gen = Rcpp::wrap(fcat_FASTA(fasta));
    return rcpp_result_gen;
END_RCPP
}
// tryptic_digest_FASTA
StringVector tryptic_digest_FASTA(const StringVector& fasta);
RcppExport SEXP _protViz_tryptic_digest_FASTA(SEXP fastaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type fasta(fastaSEXP);
    rcpp_result_gen = Rcpp::wrap(tryptic_digest_FASTA(fasta));
    return rcpp_result_gen;
END_RCPP
}
// number_of_tryptic_peptides_FASTA
int number_of_tryptic_peptides_FASTA(const StringVector& fasta0);
RcppExport SEXP _protViz_number_of_tryptic_peptides_FASTA(SEXP fasta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type fasta0(fasta0SEXP);
    rcpp_result_gen = Rcpp::wrap(number_of_tryptic_peptides_FASTA(fasta0));
    return rcpp_result_gen;
END_RCPP
}
// findNN_
IntegerVector findNN_(const NumericVector& q, const NumericVector& vec, bool check);
RcppExport SEXP _protViz_findNN_(SEXP qSEXP, SEXP vecSEXP, SEXP checkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< bool >::type check(checkSEXP);
    rcpp_result_gen = Rcpp::wrap(findNN_(q, vec, check));
    return rcpp_result_gen;
END_RCPP
}
