# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcat.FASTA <- function(fasta) {
    .Call(`_protViz_fcat_FASTA`, fasta)
}

tryptic_digest.FASTA <- function(fasta) {
    .Call(`_protViz_tryptic_digest_FASTA`, fasta)
}

