# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcat_FASTA <- function(fasta) {
    .Call('_protViz_fcat_FASTA', PACKAGE = 'protViz', fasta)
}

tryptic_digest_FASTA <- function(fasta) {
    .Call('_protViz_tryptic_digest_FASTA', PACKAGE = 'protViz', fasta)
}

number_of_tryptic_peptides_FASTA <- function(fasta0) {
    .Call('_protViz_number_of_tryptic_peptides_FASTA', PACKAGE = 'protViz', fasta0)
}

findNN_ <- function(q, vec, check = FALSE) {
    .Call('_protViz_findNN_', PACKAGE = 'protViz', q, vec, check)
}

